##
# Why YAML is not a great format:
# - No distinction between available/required attributes vs.
#   those that you can define by yourself (aka not in any docs)
# - No proper linting or jumping to source definitions
##
security:
  encoders:
    App\Entity\User: bcrypt
  providers:
    # Can be any identifier
    database_users_xxx:
      entity: { class: App\Entity\User, property: password  }
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: true
      pattern: ^/
