# 1:1 from udemy course - Slightly deprecated but still working.
security:
  encoders:
    # Define object which holds user object after? auth
    # See in Profiler: Symfony\Component\Security\Core\User\InMemoryUser
    Symfony\Component\Security\Core\User\User: plaintext

  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  providers:
    in_memory:
      memory:
        users:
          john:
            password: helloJohn
            roles: 'ROLE_USER'
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: true

      # activate different ways to authenticate

      # ~ = Default config
      http_basic: ~

      # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

      # form_login: true
      # https://symfony.com/doc/current/security/form_login_setup.html

  # Easy way to control access for large sections of your site
  # Note: Only the *first* access control that matches will be used
  access_control:
    - { path: ^/micropost, roles: ROLE_USER }
    # - { path: ^/profile, roles: ROLE_USER }
