twig:
  default_path: '%kernel.project_dir%/templates'
  # debug: '%kernel.debug%'
  globals:
    message: 'Hello from twig.yaml'
  # Part of Symfony/Twig-Bridge: \vendor\symfony\twig-bridge\Resources\views\Form\*
  form_themes: ['bootstrap_4_layout.html.twig']

when@test:
  twig:
    strict_variables: true
